---
- name: Install nginx
  yum:
    name: nginx
  become: yes

- name: Start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Configure root page
  copy:  
    src: index.html
    dest: /usr/share/nginx/html
  become: yes
  notify: Restart nginx