---
- name: Import vpc creation tasks
  import_tasks: vpc.yml

- name: Get controller machine public IP
  command: curl -4 https://api.ipify.org/
  register: public_ip

- name: Create Security Group/Firewall
  ec2_group:
    name: basic_app
    description: sg for basic app
    vpc_id: "{{ basic_app_vpc.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
        - 22
        cidr_ip: "{{ public_ip.stdout }}/32"
        rule_desc: allow ssh from my ansible controller machine
      - proto: tcp
        ports:
        - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: allow web access from anywhere
    rules_egress:
      - proto: tcp
        ports: 
          - 80
          - 443
        cidr_ip: 0.0.0.0/0
        rule_desc: allow http and https to outside world
  register: basic_app_sg


- name: Create ssh keypair
  ec2_key:
    name: basic_app_key
    region: "{{ aws_region }}"
  register: basic_app_key
  notify: Save the private key into pem file

- name: Create EC2 instance for basic app
  ec2_instance:
    key_name: "{{ basic_app_key.key.name }}"
    region: "{{ aws_region }}"
    instance_type: t2.micro
    image_id: ami-0b72821e2f351e396
    security_group:  "{{ basic_app_sg.group_id }}"
    exact_count: 1
    vpc_subnet_id: "{{ basic_app_subnet.subnet.id }}"
    wait: yes
    tags:
      Name: basic_app
      module: ec2
  register: basic_app_ec2

- name: Add ec2 instance to in-memory inventory
  add_host:
    name: "{{ basic_app_ec2.instances[0].public_ip_address }}"
    groups: aws_ec2
    ansible_user: ec2-user  
    ansible_ssh_private_key_file: "{{ inventory_dir }}/basic_app_key.pem"

- name: Wait for SSH port to come up on newly created ec2 instance
  wait_for:
    delay: 10
    timeout: 300
    port: 22
    host: "{{ basic_app_ec2.instances[0].public_ip_address }}"
