---
- name: Create VPC
  ec2_vpc_net:
    name: basic_app
    cidr_block: 10.0.0.0/16
    region: "{{ aws_region }}"
    tags:
      module: ec2_vpc_net
  register: basic_app_vpc

- name: Create Internet Gateway
  ec2_vpc_igw:
    region: "{{ aws_region }}"
    vpc_id: "{{ basic_app_vpc.vpc.id }}"
    tags:
      module: ec2_vpc_igw
      Name: basic_app
  register: igw

- name: Create subnet
  ec2_vpc_subnet:
    region: "{{ aws_region }}"
    vpc_id: "{{ basic_app_vpc.vpc.id }}"
    cidr: 10.0.0.0/24
    map_public: yes
    tags:
      Name: basic_app
      module: ec2_vpc_subnet
  register: basic_app_subnet

- name: Set up public subnet route table
  ec2_vpc_route_table:
    region: "{{ aws_region }}"
    vpc_id: "{{ basic_app_vpc.vpc.id }}"
    tags:
      Name: basic_app
      module: ec2_vpc_route_table
    subnets:
      - "{{ basic_app_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: public_route_table
